simtime:
  hour: 21
  minute: 45
  second: 30

connection: iobroker-local

local-websocket:
  type: iobroker-websocket
  url: ws://localhost:3001


iobroker-local:
  type: iobroker-websocket
  url: ws://localhost:3000
  
iobroker-home:
  type: iobroker-websocket
  url: ws://iobroker-expert.local:3000

6WayButton:
  buttons: 6

EntranceSwitch:
  buttons: 6